{% set name = "azure-storage-file-datalake" %}
{% set version = "12.23.0b1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace("-", "_") }}-{{ version }}.tar.gz
  sha256: 26bf9d027208fd43ed56b7fa0ccad99c5cd0b9efc84b6ecdecb00c66923da470

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - azure-core >=1.30.0
    - azure-storage-blob >=12.28.0b1
    - typing-extensions >=4.6.0
    - isodate >=0.6.1
  run_constrained:
    # azure-core[aio]>=1.30.0 -> https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/core/azure-core/pyproject.toml#L32
    - aiohttp >=3.0

# ModuleNotFoundError: No module named 'devtools_testutils'
test:
  imports:
    - azure.storage.filedatalake
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/storage/azure-storage-file-datalake
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: This preview package for Python includes ADLS Gen2 specific API support made available in Storage SDK
  description: This preview package for Python includes ADLS Gen2 specific API support made available in Storage SDK
  doc_url: https://aka.ms/azsdk-python-storage-filedatalake-ref
  dev_url: https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/storage/azure-storage-file-datalake

extra:
  skip-lints:
    - invalid_url
  recipe-maintainers:
    - dhirschfeld
