{% set name = "azure-storage-file-datalake" %}
{% set version = "12.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: 14817be7944e081aeea1ab9df6a9a2deeaccb715994c2a1455b9d660a263e130

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - azure-core >=1.24.2,<2.0.0
    - msrest >=0.7.1
    - azure-storage-blob >=12.14.1,<13.0.0

test:
  imports:
    - azure
    - azure.storage
    - azure.storage.filedatalake

about:
  home: https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/storage/azure-storage-file-datalake
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: This preview package for Python includes ADLS Gen2 specific API support made available in Storage SDK
  doc_url: https://aka.ms/azsdk-python-storage-filedatalake-ref

extra:
  recipe-maintainers:
    - dhirschfeld
