{% set name = "azure-storage-file-datalake" %}
{% set version = "12.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: ddaa9aa3415dd53b5e21ccd1c3e400d7b20c1ee5d1f7c856059539230c2c5932

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - azure-core >=1.10.0,<2.0.0
    - msrest >=0.6.21
    - azure-storage-blob >=12.8.0b1,<13.0.0

test:
  imports:
    - azure
    - azure.storage
    - azure.storage.filedatalake

about:
  home: https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/storage/azure-storage-file-datalake
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: This preview package for Python includes ADLS Gen2 specific API support made available in Storage SDK
  doc_url: https://aka.ms/azsdk-python-storage-filedatalake-ref

extra:
  recipe-maintainers:
    - dhirschfeld
