{% set name = "azure-storage-file-datalake" %}
{% set version = "12.22.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace("-", "_") }}-{{ version }}.tar.gz
  sha256: 9aed0d35f3327baeeb11b1950b140f97b356cfd368fc2cd105c32c820c49af77

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - azure-core >=1.30.0
    - azure-storage-blob >=12.27.0
    - typing-extensions >=4.6.0
    - isodate >=0.6.1

# ModuleNotFoundError: No module named 'devtools_testutils'
test:
  imports:
    - azure
    - azure.storage
    - azure.storage.filedatalake
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/storage/azure-storage-file-datalake
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: This preview package for Python includes ADLS Gen2 specific API support made available in Storage SDK
  description: This preview package for Python includes ADLS Gen2 specific API support made available in Storage SDK
  doc_url: https://aka.ms/azsdk-python-storage-filedatalake-ref
  dev_url: https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/storage/azure-storage-file-datalake

extra:
  skip-lints:
    - invalid_url
  recipe-maintainers:
    - dhirschfeld
